--- Makefile	2013-08-22 14:52:24.714990785 +0200
+++ Makefile.patch	2013-08-22 15:04:28.477653314 +0200
@@ -12,7 +12,7 @@
 CPPFLAGS = -fPIC -DDELTARPM_64BIT -DBSDIFF_NO_SUF -DRPMDUMPHEADER=\"$(rpmdumpheader)\" $(zlibcppflags)
 LDLIBS = -lbz2 $(zlibldflags) -llzma
 LDFLAGS =
-PYTHONS = python python3
+PYTHONS = python2 python3
 
 all: makedeltarpm applydeltarpm rpmdumpheader makedeltaiso applydeltaiso combinedeltarpm fragiso